# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_instructors',
            field=models.ManyToManyField(blank=True, to='Feeder11.Instructor'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, to='Feeder11.Student'),
        ),
    ]
