# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder11', '0002_auto_20161030_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_sem',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_year',
            field=models.PositiveIntegerField(default=2016),
        ),
    ]
