# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder11', '0004_auto_20161031_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_instructors',
        ),
    ]
