# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder11', '0005_remove_courses_course_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='deadline_course',
        ),
        migrations.AddField(
            model_name='courses',
            name='assignment_deadline',
            field=models.ManyToManyField(blank=True, to='Feeder11.Deadline'),
        ),
        migrations.AddField(
            model_name='courses',
            name='feedback_forms',
            field=models.ManyToManyField(blank=True, to='Feeder11.FeedbackForm'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='feedback_deadline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Feeder11.Deadline'),
        ),
    ]
