# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder11', '0006_auto_20161101_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer_question',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_student',
        ),
        migrations.AddField(
            model_name='question',
            name='question_answers',
            field=models.ManyToManyField(blank=True, to='Feeder11.Answers'),
        ),
    ]
