# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder11', '0007_auto_20161105_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='feedback_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
