# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder11', '0008_feedbackform_feedback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
